// <auto-generated />
using System;
using ISQExplorer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ISQExplorer.Migrations
{
    [DbContext(typeof(ISQExplorerContext))]
    partial class ISQExplorerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ISQExplorer.Models.CourseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ISQExplorer.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("DepartmentModel");
                });

            modelBuilder.Entity("ISQExplorer.Models.ISQEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("Crn")
                        .HasColumnType("integer");

                    b.Property<double>("MeanGpa")
                        .HasColumnType("double precision");

                    b.Property<int>("NEnrolled")
                        .HasColumnType("integer");

                    b.Property<int>("NResponded")
                        .HasColumnType("integer");

                    b.Property<double>("Pct1")
                        .HasColumnType("double precision");

                    b.Property<double>("Pct2")
                        .HasColumnType("double precision");

                    b.Property<double>("Pct3")
                        .HasColumnType("double precision");

                    b.Property<double>("Pct4")
                        .HasColumnType("double precision");

                    b.Property<double>("Pct5")
                        .HasColumnType("double precision");

                    b.Property<double>("PctA")
                        .HasColumnType("double precision");

                    b.Property<double>("PctAMinus")
                        .HasColumnType("double precision");

                    b.Property<double>("PctB")
                        .HasColumnType("double precision");

                    b.Property<double>("PctBMinus")
                        .HasColumnType("double precision");

                    b.Property<double>("PctBPlus")
                        .HasColumnType("double precision");

                    b.Property<double>("PctC")
                        .HasColumnType("double precision");

                    b.Property<double>("PctCPlus")
                        .HasColumnType("double precision");

                    b.Property<double>("PctD")
                        .HasColumnType("double precision");

                    b.Property<double>("PctF")
                        .HasColumnType("double precision");

                    b.Property<double>("PctNa")
                        .HasColumnType("double precision");

                    b.Property<double>("PctWithdraw")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("Crn", "Season", "Year");

                    b.ToTable("IsqEntries");
                });

            modelBuilder.Entity("ISQExplorer.Models.ProfessorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NNumber");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("ISQExplorer.Models.CourseModel", b =>
                {
                    b.HasOne("ISQExplorer.Models.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ISQExplorer.Models.ISQEntryModel", b =>
                {
                    b.HasOne("ISQExplorer.Models.CourseModel", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("ISQExplorer.Models.ProfessorModel", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("ISQExplorer.Models.ProfessorModel", b =>
                {
                    b.HasOne("ISQExplorer.Models.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
