// <auto-generated />
using System;
using ISQExplorer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISQExplorer.Migrations
{
    [DbContext(typeof(ISQExplorerContext))]
    partial class ISQExplorerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISQExplorer.Models.IsqEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Crn")
                        .HasColumnType("int");

                    b.Property<double>("MeanGpa")
                        .HasColumnType("float");

                    b.Property<int>("NEnrolled")
                        .HasColumnType("int");

                    b.Property<int>("NResponded")
                        .HasColumnType("int");

                    b.Property<int>("NTotal")
                        .HasColumnType("int");

                    b.Property<double>("Pct1")
                        .HasColumnType("float");

                    b.Property<double>("Pct2")
                        .HasColumnType("float");

                    b.Property<double>("Pct3")
                        .HasColumnType("float");

                    b.Property<double>("Pct4")
                        .HasColumnType("float");

                    b.Property<double>("Pct5")
                        .HasColumnType("float");

                    b.Property<double>("PctA")
                        .HasColumnType("float");

                    b.Property<double>("PctAMinus")
                        .HasColumnType("float");

                    b.Property<double>("PctB")
                        .HasColumnType("float");

                    b.Property<double>("PctBMinus")
                        .HasColumnType("float");

                    b.Property<double>("PctBPlus")
                        .HasColumnType("float");

                    b.Property<double>("PctC")
                        .HasColumnType("float");

                    b.Property<double>("PctCPlus")
                        .HasColumnType("float");

                    b.Property<double>("PctD")
                        .HasColumnType("float");

                    b.Property<double>("PctF")
                        .HasColumnType("float");

                    b.Property<double>("PctWithdraw")
                        .HasColumnType("float");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("IsqEntries");
                });

            modelBuilder.Entity("ISQExplorer.Models.ProfessorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("ISQExplorer.Models.IsqEntryModel", b =>
                {
                    b.HasOne("ISQExplorer.Models.ProfessorModel", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");
                });
#pragma warning restore 612, 618
        }
    }
}
